api_platform:
    title: 'Symfony Stage REST API 2'
    description: 'API 2 qui permet le CRUD et la consultation de clients sous Symfony avec API PLATFORM.'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
          apiKey:
            name: Authorization
            type: header
