api_platform:
    title: 'Symfony Stage REST API 1'
    description: 'API 1 qui permet la consultation du personnel de plusieurs agences, user, article et comment sous Symfony avec API PLATFORM.'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
          apiKey:
            name: Authorization
            type: header